<?php
/**
 * @license Copyright 2011-2014 BitPay Inc., MIT License
 * @see https://github.com/bitpay/magento-plugin/blob/master/LICENSE
 */
?>
<div style="background-color:#002855;padding:5px;color:#ffffff">
    <img src="https://raw.githubusercontent.com/bitpay/bitpay-brand/master/bitpay-logo-primary.png" alt="BitPay" witdth="113" height="44" />
    <a style="color:#ffffff;font-family:'Ubuntu',sans-serif;text-decoration:none;margin:15px" href="https://support.bitpay.com/?ref=magento">Support</a>
    <a style="color:#ffffff;font-family:'Ubuntu',sans-serif;text-decoration:none;margin:15px" href="https://bitpay.com/start?ref=magento">Sign Up</a>
    <a style="color:#ffffff;font-family:'Ubuntu',sans-serif;text-decoration:none;margin:15px" href="https://bitpay.com/merchant-login?ref=magento">Login</a>
</div>
